# _config.yml

# ----------------- #
#  Site Settings    #
# ----------------- #

# The title of your site. Appears in the browser tab and search results.
title: CFMSE

# The description of your site. Used by search engines.
description: Flowing Straighter with Conditional Flow Matching for Accurate Speech Enhancement

# The name of your GitHub repository (e.g., "my-awesome-project")
# This is used to build the correct links and paths.
# IMPORTANT: Replace <YOUR_REPOSITORY_NAME> with your repo's name.
baseurl: "/cfmse"

# The full URL to your site.
# IMPORTANT: Replace <YOUR_USERNAME> and <YOUR_REPOSITORY_NAME>
# This is used for generating sitemaps and SEO data.
url: "https://Mattias421.github.io"

# A path to an image that represents your project.
# This is used for social media previews (e.g., when you share a link on Twitter).
# The image should be in your repository.
logo: uos_cd_ukri_square.pdf


# ----------------- #
#  Author & Socials #
# ----------------- #
# Used by some themes to display author information and social media links.

author:
  name: Mattias Cross
  email: crossmattias@gmail.com

# Your social media usernames, without the "@".
# Used by the jekyll-seo-tag plugin and some themes.

github:
  username: Mattias421


# ----------------- #
#  Build Settings   #
# ----------------- #

# Select the theme for your site.
theme: jekyll-theme-minimal

# Specify the Markdown processor.
markdown: kramdown

# Add any Jekyll plugins here.
# 'jekyll-seo-tag' is highly recommended for SEO.
# 'jekyll-feed' creates an RSS feed.
# These are supported by GitHub Pages.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude these files from the final build.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
